### ISSUE TITLE
Add support for Arduino IDE

### ISSUE THREAD

**Issue by ciband** [Ark-IoT/Ark-Cpp#14]

**Comment by ciband** [comment]
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

**Comment by per1234** [comment]
Very few of the keywords defined in your keywords.txt actually work. This is how the keywords are colored in the Arduino IDE after installing the library:
![clipboard01](https://user-images.githubusercontent.com/8572152/37938140-98e296b2-3111-11e8-8b27-fae704287010.png)
There is the basic problem of not using a [single true tab as keyword separator](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywordstxt-format) but there is also the issue that the Arduino IDE does not support this sort of keyword: `ARK::Account`.
A solution would be to add a keyword definition for each word:
```
ARK	KEYWORD1
...
Account	KEYWORD1
```
![clipboard02](https://user-images.githubusercontent.com/8572152/37938347-369b4750-3112-11e8-978c-7082a371faa3.png)
I'd be happy to submit a PR for this if you like.

**Comment by sleepdefic1t** [comment]
@per1234
Thank you for the great explanation.

You are definitely welcome to contribute with a PR.
We appreciate the help!

**Comment by ciband** [comment]
done and will be merged in next PR
